### ISSUE TITLE
Views for generating menu

### ISSUE THREAD

**Issue by marktopper** [spatie/laravel-menu#25]
Would it be possible that the whole code that generates the menu output could be put into views?

This makes it easier to customize, and then it could support parsing custom views in while outputting the menu as HTML, then it will use the view parsed to it.

**Comment by sebastiandedeyne** [comment]
Menu rendering doesn't happen in one big render method, each item has it's own rendering logic (e.g. a link takes care of it's own rendering). Moving this logic to views wouldn't necessarily make it easier to customise since the rendered html already is so small.

Besides that, it simply wouldn't be possible since the actual menu package (https://github.com/spatie/menu) isn't coupled to Laravel.
