### ISSUE TITLE
[QUESTION] Setting up menu with Laravel-permissions

### ISSUE THREAD

**Issue by joselfonseca** [spatie/laravel-menu#40]
Hello,

First of all thanks for all the open source packages you guys provide us, I am having a bit of a problem with the LinkIfCan method when using https://github.com/spatie/laravel-permission . I have the following.

Please note that the permissions for a user are via a role. If i check the gates they are registered.

In a Service provider loaded after the laravel permissions and laravel menu ones
```php
protected function registerMenus()
{
    $this->app->singleton('menu.sidebar', function(){
        return app(Menu::class)->addClass('sidebar-menu');
    });
}
```
Then in another service provider I have

```php
protected function setMenu()
{
    $menu = app('menu.sidebar');
    $menu->add(Html::raw('<li class="header">USUARIOS</li>'));
    $menu->linkIfCan('Listar Usuarios', '/users', 'Listar');
}
```
The item won't show up even if the user has the permission assigned and registered in the Gate.

I went to https://github.com/spatie/laravel-menu/blob/master/src/Menu.php#L152 and this `(app(Gate::class)->allows($ability, $ablityArguments)` returns false, but if I run that same line in a controller changing `$ability` by the permission it returns true, so I am lost on that one :( 

Any help is very appreciated 

Thanks!

**Comment by sebastiandedeyne** [comment]
Hmm sorry but the only thing I can say atm is that you'll have to pinpoint why it returns false by adding some debug statements in the Gate class itself...

Maybe the menu is rendered before permissions are set up? You're sure the permission name doesn't have any typos or a different case?

**Comment by apmyp1990** [comment]
Hi everyone,
I have a similar problem. 
I'm using the laravel-menu package with the laravel-persmissions package. too. 

I have created a permission, assigned it to a role, and assigned the role to my user. This works fine. 
Then I have generated a menu the middleware way using a macro like so:
`\Menu::macro('main', function () use ($request) {
            return \Menu::new()
                ->withoutWrapperTag()
                ->withoutParentTag()
                ->setActiveClassOnLink()
                ->route('preparation', 'Anstehende Termine')
                ->route('postprocessing', 'Nachbereitung')
                ->routeIfCan('administrate', 'protocols', 'Protokolle')
                ->addItemClass('nav-link')
                ->setActive($request->url());
        });`

In my application I have two User models with different connections:
`App\User;` using connection_a with database db_a and
`App\DirectoryA\User;` using connection_b with database db_b

In the auth config the first one is defined, and using `Auth::user()->can('administrate')` works fine, even in the Middleware that defines the menu.

Since I have added the menu item via `routeIfCan`, I'm getting an error. It tells 

> Base table or view not found: 1146 Table 'db_b.permissions' doesn't exist (SQL: select `permissions`.*, `model_has_permissions`.`model_id` as `pivot_model_id`, `model_has_permissions`.`permission_id` as `pivot_permission_id`, `model_has_permissions`.`model_type` as `pivot_model_type` from `permissions` inner join `model_has_permissions` on `permissions`.`id` = `model_has_permissions`.`permission_id` where `model_has_permissions`.`model_id` = 1 and `model_has_permissions`.`model_type` = App\User) 


What is going wrong here? It should use the `App\User` model. Placing a `dd()` at the point the framework throws the exception shows me the correct connection... 

Please help.
