### ISSUE TITLE
How to use translation?

### ISSUE THREAD

**Issue by khacnha** [spatie/laravel-menu#62]
I want to set multilingual for menu, but unfortunately it does not work.

**Comment by sebastiandedeyne** [comment]
Could you provide a code snippet of what you're exactly trying to achieve?

**Comment by khacnha** [comment]
I am defining the menu list in the config menu.php:
```
 $arLink = [
            [
                'icon' => 'fa fa-dashboard',
                'title' => __('Dashboard'),
                'href' => '/home',
            ],
[
                'icon' => 'fa fa-cog',
                'title' => __('Company Info'),
                'href' => 'my_company',
                'permission' => 'CompaniesController@postMyCompany',
            ]
];
Menu::macro('sidebar', function () use($arLink) {
...
});
```

But __('Company Info') not working.

So now I have used other solution to use _trans_:
```
Menu::macro('sidebar', function ($arLink) {

});
```

When calling the function, I will cast the menu list:
```
@php
 $arLink = [...]
@endphp
{{ Menu::sidebar(Auth::user(), $arLink) }}
```

**Comment by sebastiandedeyne** [comment]
This is not an issue with this package. Configuration values are loaded before translation values, so your app can't resolve the `__` calls from config files.

If all your strings are translated, make the `__` call when you're generating the menu instead.

```php
$arLink = [
            [
                'icon' => 'fa fa-dashboard',
                'title' => 'Dashboard',
                'href' => '/home',
            ],
];
```

Alternatively, store your menu structure in a PHP file you manually require instead of using a Laravel config file.
