### ISSUE TITLE
Subpage url() activation in multiple menus.

### ISSUE THREAD

**Issue by randohinn** [spatie/laravel-menu#63]
Given a use case as such:

```
Menu::macro('self_service', function () {
    return Menu::new()
        ->prepend('<b>KASUTAJA</b>')
        ->url('/ise', 'Ülevaade')
        ->setActiveFromRequest();                
});

Menu::macro('association_admin', function () {
    return Menu::new()
         ->prepend('<b>KORTERÜHISTU</b>')
         ->url('/ise/yhistu/korterid', 'Korterid')                           
         ->setActiveFromRequest();                
});
```

where the first menu is always rendered, and the second one lives inside an `if` statement, when going to `/ise/yhistu/korterid'`, the link for `/ise` in the first menu gets activated aswell. This is not wanted, is there a way to prevent this?

**Comment by sebastiandedeyne** [comment]
In this case, you could define the menu's "request root" which is never rendered active, because according to the url it's *always* active (like Home links)

```
return Menu::new()
        ->prepend('<b>KASUTAJA</b>')
        ->url('/ise', 'Ülevaade')
        ->setActiveFromRequest('/ise'); 
```

You'll need to add a conditional in the parameter if you don't always want it to behave like that though.

Additionally, you can mutate existing items afterwards with `each`, maybe that could help.

https://docs.spatie.be/menu/v2/items-in-depth/manipulating-items
