### ISSUE TITLE
Invalid Scheme using javascript:;

### ISSUE THREAD

**Issue by i6media** [spatie/laravel-menu#99]
For a dropdown menu I'm using a "javascript:;" as href in a parent item.

Whenever I add a Link method with URL: `javascript:;` on a Link object:

`Link::to("javascript:;", "Demo)`, I get a Laravel Exception on the `setActive()` method:

The scheme `javascript` isn't valid. It should be either `http` or `https`

Spatie\Url\Exceptions\InvalidArgument::invalidScheme
vendor/spatie/url/src/Exceptions/InvalidArgument.php:11

Is there any way to resolve this matter without having to enter the `<a href>` via the HTML method?

**Comment by i6media** [comment]
Reopen

**Comment by freekmurze** [comment]
We're leaving it closed as we ourselves and others haven't come across this bug.

Feel free to PR a fix, make sure to include tests.

**Comment by ChristinePHP** [comment]
I'm having the same problem. I'm using the package to output a menu for an admin panel and for some of the links I'm linking to javascript:void(0). After looking into the code I discovered that the issue is caused when a person uses the setActiveFromRequest() method because this results in the fromString() method being called Spatie\Url\Url package which the Laravel menu package uses when setActiveFromRequest() is called. The fromString method uses parse_url and the scheme parameter is seen as "javascript". The next few lines of code check the scheme and "javascript" is not seen as a valid scheme and so the error is thrown.

It would be great if this can be amended to check for the existence of url's that use javascript and avoid using parse_url on these types of url's.
